name: Build & Test
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-then-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Build
        run: |
          docker build .
    timeout-minutes: 10