name: Build & Test
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build-then-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Build
        run: |
          docker build .
      - name: Request online test
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.COMMENT_TOKEN }}
          repository: hnwyllmm/miniob_test
          issue-number: 7
          body: test ${{github.repository_owner}}
    timeout-minutes: 10
